### ISSUE TITLE
New Alldebrid API

### ISSUE THREAD

**Issue by Alldebrid** [pyload/plugins#3]
Hello,

We are the Alldebrid development team.
We are contacting you to let you know that we have set up a new API.

All documentation is available here => https://docs.alldebrid.com/

IMPORTANT: Old versions of our API (V1 / V2) will be completely disabled in 30 days. These will no longer be available / functional.
It will be necessary to switch to the new version before this delay.

Do not hesitate to contact us for any questions / problems directly => support [@] alldebrid.com

Regards,
Alldebrid staff.

**Comment by GammaC0de** [comment]
Hello, 
Test user/password is required...

**Comment by GammaC0de** [comment]
Also, There is an error with the docs:
Endpoint for login is `https://api.alldebrid.com/user/login` and not `https://api.alldebrid.com/login` as the docs says.

**Comment by Alldebrid** [comment]
Email sent!

As mentionned, we will fix the doc asap.

**Comment by GammaC0de** [comment]
Thank you for the test but please remove the Geolock protection (I did not get the PIN code to my email).

Also, it would be nice if you add `pyLoad` to https://alldebrid.com/extensions/?platform=downloaderw

**Comment by Alldebrid** [comment]
The geolock has been disabled.
We will add your tool.

**Comment by Alldebrid** [comment]
Some important modifications to our API has been made :

- Authentificated endpoint requires an agent parameter to identify your software.
- We have added an /user/hosts endpoint that give in-real-time hosters that the user can use depending of its subscription status.

The api should be stable, we don't expect to alter it too much for now, except if you have any suggestion to improve or complete our current api.

**Comment by GammaC0de** [comment]
Well, there is a problem with https://docs.alldebrid.com (I get CloudFlare error), I cannot read the docs.

**Comment by Alldebrid** [comment]
Hello, 

You are really lucky we saw your message. 

Please, as
requested use => support@alldebrid.com 

We won't be able to reply to
you from here anymore. 

The doc is up. 

Regards,
AD staff. 

Le
2017-09-15 03:51, GammaC0de a écrit : 

> Well, there is a problem with
https://docs.alldebrid.com [1] (I get CloudFlare error), I cannot read
the docs. 
> 
> --
> You are receiving this because you authored the
thread.
> Reply to this email directly, view it on GitHub [2], or mute
the thread [3].
 

Links:
------
[1] https://docs.alldebrid.com
[2]
https://github.com/pyload/pyload-plugins/issues/3#issuecomment-329655507
[3]

**Comment by Alldebrid** [comment]
Hello

Thanks for integrating our new api !
We have a couple of requests if you don't mind : 

- Your user agent has the pyload version included. When the version will change, the agent will too, and token will be invalid, forcing your users to re-loggin. Please only use something like agent=pyLoad, and send an other parameter version=0.4.9 if you want to let us know, but that's optionnal.

- Is it possible to cache the result of /user/hosts/ a bit ? Right now Pyload is hammering our api of /user/hosts/ calls, often multiple times per second for the same user, I think that's no quite efficient.

**Comment by GammaC0de** [comment]
> Your user agent has the pyload version included. When the version will change, the agent will too, and token will be invalid, forcing your users to re-loggin. Please only use something like agent=pyLoad, and send an other parameter version=0.4.9 if you want to let us know, but that's optionnal.

Plugin updated, now  agent=pyLoad and version=current_version

> Right now Pyload is hammering our api of /user/hosts calls, often multiple times per second for the same user

This is very weird:
pyLoad do cache the hoster list.
pyLoad default behavior is to refresh for the hoster list every 12 hours unless the user explicitly changes the value in the plugin configuration.
Does this happen for **all** pyLoad users or just some? maybe they are using broken installation or updated plugins? 

If this happens to just few users, you can see which users have bad installation and direct them to here so I can investigate this.


I also tested this and downloaded 22 files (6 GB approx) with just one call to /user/hosts...

**Comment by Alldebrid** [comment]
Thanks for the agent fix.

It seems that it's only 4/5 users that are constantly hitting our api, check this log : https://pastebin.com/62GyYSJP (I'have obfuscated IP and tokens a bit). Those users seems to use pyLoad from a dedicated server, which are blocked on our /link/unlock endpoint, maybe some edge case when the downloads fail or something like this ?

We will contact them tomorrow if this behavior remains to check with them directly why that's happening, if you can't reproduce this (weird) behavior.

For the caching part, we are considering sending a 'validFor' value in our api response o give an indication of good cache duration, is this something you'll be interested to use ?

**Comment by GammaC0de** [comment]
> We will contact them tomorrow if this behavior remains to check with them directly why that's happening

Great, you can tell them to open an issue here if they need help reinstalling.

> For the caching part, we are considering sending a 'validFor' value in our api response to give an indication of good cache duration, is this something you'll be interested to use

I don't understand how a 'validFor' value will be used and what it is good for..

**Comment by Alldebrid** [comment]
This would be an indication of how long you should cache the /user/hosts/ result.

**Comment by Alldebrid** [comment]
The /user/hosts/ caching issue seems to persist, some users are using the last version (the version parameter is sent apart from the agent), and they still are fetching the /user/hosts/ endpoint multiple times per seconds (10/15+ times/seconds... It's that bad).

We'll try to contact some of them to try to debug this behavior with them, but this behavior seems tro persist even in the last version.

**Comment by GammaC0de** [comment]
Can you confirm that the problem does not occur on other ptLoad users? (the majority?)

The plugin relies on other plugins, maybe the root of the problem relies there, it would be the best that they would refresh all the plugins or even reinstall.

**Comment by Alldebrid** [comment]
11 users are spamming our api for now, 6 more than yesterday, all on the new version (agent and version apart) except for one. They spam at different rate, from 2-3 hits/second to 15-20 hits/second...

We contacted 2 users to try to get a hold on some debug infos.

**Comment by Alldebrid** [comment]
[pyload.log.txt](https://github.com/pyload/pyload-plugins/files/1319044/pyload.log.txt)
I managed to reproduce this issue, installed pyload 0.4.9, updated the plugins, made a few downloads, nothing to report at 12h43. Then after some time, the bug occured, and pyload started to requests the hoster list for Alldebrid over 10 times per second.

Pyload seems to relogin the Alldebrid account, and then go in a infinite loop of grabing the hoster list, at 18:43:33. 


I'have attached the console output in debug mode. If you need anything to help hunt this bug please ask.

**Comment by GammaC0de** [comment]
OK, with your helpful hints I managed to reproduce this issue too.

I updated the plugin and it should be fixed now.

Can you confirm that? 
Of-course we have to wait I'd say about at least 24 hours until the plugin gets updated and maybe also pyLoad restart would be required.

Thanks for patience and for spotting this nasty bug :)

**Comment by Alldebrid** [comment]
Glad you found it, we'll wait 24 hours to see if the pyLoad heavy api hitters are gone.

**Comment by Alldebrid** [comment]
I confirm the bugfix works, we only have 2 pyLoad user left with the issue. Great work, thanks.
